### ISSUE TITLE
Unable to add a special parameter in a step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#357]
### Expected behavior

Should be able to add a special parameter in a step
### Actual behavior

Unable to add a special parameter in a step
### Steps to reproduce
1. Create a spec

```
Something
=========

wwwwwwww
--------
* Verify "email" text
* Verify "email" text

```
1. Give implementation

```
    @Step("Verify <email> text")
    public void implementation7(String argEmail) {
    }
```
1. Create email.txt

```
Id,Name
1,The Way to Go On
2,Ivo Jay Balbaert
```
1. Refactor 'Verify "email" text' to 'Verify "email" file:specs/test/email.txttext'
2. It does not refactor the step or gives me a compilation error
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by sriv** [comment]
Works on Gauge 0.6.3.

Refactoring Verify "email" file:specs/test/email.txttext yields:

Step :

```
* Verify "email" file:specs/test/email.txttext
```

and implementation:

```
    @Step("Verify <email> file:specs/test/email.txttext")
    public void implementation7(String argEmail) {
    }
```
